version: '3.7'
services:
  nwserver:
    hostname: nwserver
    # reference https://hub.docker.com/r/nwnxee/unified/tags for more precise versioning
    image: nwnxee/unified:latest
    restart: unless-stopped
    environment:
    - NWN_SERVERNAME=Docker Template
    volumes:
    - ${PWD-.}/server/:/nwn/home
    - ${PWD-.}/logs:/nwn/run/logs.0
    - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
    ports:
    - '5121:5121/udp'
